version: "3.9"
services:
  db:
    image: postgres:17.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=course_plataform_video
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
